[project]
name = "walutomat-ha"
version = "0.1.1"

[tool.pytest.ini_options]
addopts = "--cov=custom_components.walutomat --cov-report=term-missing"
asyncio_mode = "auto"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-homeassistant-custom-component==0.13.205",
]
